---
galaxy_info:
  role_name: bootptab
  author: Paul Finley
  description: Ansible role for modifying bootptab file on AIX.
  company: IBM

  license: GPL-3.0-only

  min_ansible_version: 2.9

  platforms:
    - name: AIX
      versions:
        - all

  galaxy_tags: [aix]
  dependencies: []
