---
# Always required
# NIM Master that will be used in migrating the required Master machine

nim_master_migration_master_a: ""

# Always Required
# NIM master that needs to be migrated

nim_master_migration_master_b: ""

# Always required
# NIM Master A's hostname

nim_master_migration_master_a_hostname: ""

# Always required
# NIM Master B's hostname

nim_master_migration_master_b_hostname: ""

# Always required
# Location where lpp_source is present.

nim_master_migration_lpp_source: ""

# Always required
# Location where spot is located.

nim_master_migration_spot: ""

# Always required
# Specifies the Alternate disk that would be used for migration

nim_master_migration_alt_disk: ""

# Always required
# Specifies the location where NIM master fileset is located on the controller node.

nim_master_migration_nim_master_fileset_src: ""

# Always required
# Specifies the location where NIM master fileset is located on the nim_master_migration_master_b machine

nim_master_migration_nim_master_fileset_dest: ""

# Always required
# Specifies the location where Alt_disk_install fileset is located

nim_master_migration_alt_disk_install_fileset: ""

# Optional
# Name and location of the file where database backup will be stored

nim_master_migration_db_filename: ~/db_backup

# Optional
# Name and location of the file where database backup file will be stored on the controller node

nim_master_migration_db_file_controller: ~/db_backupfile

# Always required
# Specifies the phase of operations that will take place.

nim_master_migration_phase: ""
