---
############################################################
# DISCUSSION:
# 1. Add force option
# - if 'true' then it will delete an existing 'dflt_spot'
# and create a new one from the specified lpp_source
# - if 'false then it will skip the automatic creation
# of a SPOT resource from a lpp_source if 'dflt_spot'
# already exists
# 2. Add feature to specify an existin SPOT resource
############################################################

- name: "Fetch the location of the lpp_source"
  block:
    - ibm.power_aix.nim_resource:
        action: show
        name: "{{ lpp_source }}"
      register: lpp_source_query

    - set_fact:
        lpp_source_info: "{{ lpp_source_query.nim_resources.values() | first }}"
        location_pattern: "(/\\S+)(?=/)"

    - set_fact:
        lpp_source_location: "{{ lpp_source_info.location |
          regex_search(location_pattern, '\\0') | join('\n') }}"

############################################################
# NOTE: if SPOT is not specified then create a SPOT
# resource from a specified LPP source
#
# e.g. stderr if SPOT resource of the same name
# already exists
# nim -o define -t spot -a location=/nim1 -a server=master -a source=lpp_2134A_730 dflt_spot
# 0042-001 nim: processing error encountered on "master":
# 0042-081 m_mkspot: a resource already exists on "master" at
#   location "/nim1/dflt_spot/usr"; due to NFS export restrictions, the
#   new location "/nim1/dflt_spot/usr" may not be used
############################################################

- name: "create SPOT resource from {{ lpp_source }}"
  ibm.power_aix.nim_resource:
    action: create
    name: "dflt_{{ lpp_source }}_spot"
    object_type: spot
    attributes:
      source: "{{ lpp_source }}"
      location: "{{ lpp_source_location }}"
  register: result

- name: "if SPOT resource already exists then query if 'bos.alt_disk_install.rte is installed'"
  block:
    - debug:
        msg: "SPOT resource 'dflt_{{ lpp_source }}_spot' already exists."

    - ibm.power_aix.nim_resource:
        action: show
        name: "dflt_{{ lpp_source }}_spot"
        showres:
          fetch_contents: true
          max_retries: "{{ dflt_max_retries }}"
          retry_wait_time: "{{ dflt_retry_wait_time }}"
      register: spot_query
  when: result.stderr.find( "0042-081" ) != -1

- name: "Set SPOT resource to be used"
  block:
    - set_fact:
        spot: "dflt_{{ lpp_source }}_spot"
    - set_fact:
        spot_fileset: "{{ spot_query['nim_resources'][spot]['contents'] }}"

- include_tasks: "add_alt_disk_install_fileset.yml"
  when: >
    result.stderr.find( "0042-081" ) == -1 or
    spot_fileset['bos.alt_disk_install.rte'] is not defined
