---
############################################################
# DISCUSSION:
# 1. Add force option
# - if 'true' then it will delete an existing 'dflt_spot'
# and create a new one from the specified nim_alt_disk_migration_lpp_source
# - if 'false then it will skip the automatic creation
# of a SPOT resource from a nim_alt_disk_migration_lpp_source if 'dflt_spot'
# already exists
# 2. Add feature to specify an existin SPOT resource
############################################################

- name: Fetch the location of the nim_alt_disk_migration_lpp_source
  block:
    - ibm.power_aix.nim_resource:
        action: show
        name: "{{ lnim_alt_disk_migration_pp_source }}"
      register: lpp_source_query

    - ansible.builtin.set_fact:
        lpp_source_info: "{{ lpp_source_query.nim_resources.values() | first }}"
        location_pattern: (/\S+)(?=/)

    - ansible.builtin.set_fact:
        lpp_source_location: "{{ lpp_source_info.location | regex_search(location_pattern, '\\0') | join('\n') }}"

############################################################
# NOTE: if SPOT is not specified then create a SPOT
# resource from a specified LPP source
#
# e.g. stderr if SPOT resource of the same name
# already exists
# nim -o define -t spot -a location=/nim1 -a server=master -a source=lpp_2134A_730 dflt_spot
# 0042-001 nim: processing error encountered on "master":
# 0042-081 m_mkspot: a resource already exists on "master" at
#   location "/nim1/dflt_spot/usr"; due to NFS export restrictions, the
#   new location "/nim1/dflt_spot/usr" may not be used
############################################################

- name: Create SPOT resource from {{ nim_alt_disk_migration_lpp_source }}
  ibm.power_aix.nim_resource:
    action: create
    name: dflt_{{ nim_alt_disk_migration_lpp_source }}_spot
    object_type: spot
    attributes:
      source: "{{ nim_alt_disk_migration_lpp_source }}"
      location: "{{ lpp_source_location }}"
  register: result

- name: If SPOT resource already exists then query if 'bos.alt_disk_install.rte is installed'
  when: result.stderr.find( "0042-081" ) != -1

  block:
    - ansible.builtin.debug:
        msg: SPOT resource 'dflt_{{ nim_alt_disk_migration_lpp_source }}_spot' already exists.

    - ibm.power_aix.nim_resource:
        action: show
        name: dflt_{{ nim_alt_disk_migration_lpp_source }}_spot
        showres:
          fetch_contents: true
          max_retries: "{{ nim_alt_disk_migration_dflt_max_retries }}"
          retry_wait_time: "{{ nim_alt_disk_migration_dflt_retry_wait_time }}"
      register: spot_query
- name: Set SPOT resource to be used
  block:
    - ansible.builtin.set_fact:
        spot: dflt_{{ nim_alt_disk_migration_lpp_source }}_spot
    - ansible.builtin.set_fact:
        spot_fileset: "{{ spot_query['nim_resources'][spot]['contents'] }}"

- ansible.builtin.include_tasks: add_alt_disk_install_fileset.yml
  when: >
    result.stderr.find( "0042-081" ) == -1 or
    spot_fileset['bos.alt_disk_install.rte'] is not defined
