# Copyright (c) IBM Corporation 2020
---
- name: Enable inetd services
  ansible.builtin.replace:
    path: /etc/inetd.conf
    regexp: '^#({{ inetd_services | join("\s|") }}\s)'
    replace: '\1'
    backup: "{{ inetd_backup | bool }}"
    owner: root
    group: system
    mode: "0664"
  when: inetd_state == 'enabled' and inetd_services
  notify: restart inetd

- name: Disable inetd services
  ansible.builtin.replace:
    path: /etc/inetd.conf
    regexp: '^({{ inetd_services | join("\s|") }}\s)'
    replace: '#\1'
    backup: "{{ inetd_backup | bool }}"
    owner: root
    group: system
    mode: "0664"
  when: inetd_state == 'disabled' and inetd_services
  notify: restart inetd
