---

- name: "nim_alt_disk_migration demo"
  hosts: "{{ target_system }}"
  gather_facts: false
  remote_user: root
  vars:
    nim_client_v: p9zpa-ansible-test2
    target_disk_v: hdisk1
    target_disk_policy_v: minimize
    lpp_source_v: lpp_72V_2114
    spot_v: spot_72V_2114
    force_target_disk: true
    validate_nim_resources_v: true
    perform_migration_v: true
    test_case_number: 1
  collections:
    - ibm.power_aix
  tasks:

    # TEST10 Migration with no lpp_source varaiable - expect -  FAILURE
    - set_fact:
         test_case: "TEST10"
         test_rc: false
    - set_fact:
         test_exec: "{{ test_case }} Migration with no lpp_source varaiable - expect -  FAILURE"
    - debug: var=test_exec


    - name: "{{ test_exec }}"
      block:
        - import_role:
            name: ibm.power_aix.nim_alt_disk_migration
          vars:

            nim_client: "{{ nim_client_v }}"
            target_disk:
              disk_name: ""
              disk_size_policy: "{{ target_disk_policy_v }}"
              force: "{{ force_target_disk }}"
#            lpp_source: ""
            reboot_client: false
            spot: "{{ spot_v }}"
            control_phases:
               validate_nim_resources: false
               perform_migration: true
            debug_skip_nimadm: true
      rescue:
        - debug:
            msg: "Expected test failure"
        - set_fact:
           test_rc: true

    - debug: msg="End of {{ test_exec }}"
    - assert:
        fail_msg: "FAILURE: {{ test_exec }}"
        that: test_rc
    - debug: msg="{{ test_exec }}"
