---
- name: Check if the file already exists
  stat:
    path: "{{ db_filename }}"
  delegate_to: "{{ master_b }}"
  register: filestatus

- block:
    - name: Copy file from controller node to {{ master_b }}
      copy:
        src: "{{ db_file_controller }}"
        dest: "{{ db_filename }}"
      register: syncfile

    - name: Check status
      debug:
        msg: Backup file transferred successfully
      when: syncfile.changed
  when: not filestatus.stat.exists