---
- name: Check if the file exists
  ansible.builtin.stat:
    path: "{{ db_filename }}"
  register: filestatus
  delegate_to: "{{ master_b }}"

- block:
    - name: Copy file to Controller node
      ansible.builtin.fetch:
        src: "{{ db_filename }}"
        dest: "{{ db_file_controller }}"
      delegate_to: "{{ master_b }}"
      register: syncfile

    - name: Check status
      ansible.builtin.debug:
        msg: Backup file transferred successfully
      when: syncfile.changed

  when: filestatus.stat.exists
