# Copyright (c) IBM Corporation 2020
---
# TASKS THAT WILL BE PERFORMED

# 1. Do NIM Database backup of NIM Master B.
# 2. Unconfigure the NIM Database.
# 3. Uninstall the NIM master fileset from NIM Master B.
# 4. Add the NIM Master B as a “standalone” client to NIM Master A.
# 5. Perform “nimadm” migration using available “non-rootvg” physical volume of NIM client.
# 6. After migration is completed, reboot the NIM client and ensure that the NIM client has been migrated to the new version.
# 7. Install “bos.sysmgt.nim.master” fileset of new oslevel to NIM Master B and configure it as a “NIM Master”.
# 8. Restore the NIM DB.

###############################################################################

- name: Fail if master_a is not specified
  ansible.builtin.fail:
    msg: "NIM Master machine(master_a) is not specified"
  when: master_a  | length > 0

- name: Fail if master_b is not specified
  ansible.builtin.fail:
    msg: "NIM Master machine(master_b) is not specified"
  when: master_b | length > 0

- name: "Fail if Alternate disk has not been specified"
  ansible.builtin.fail:
    msg: "No alternate disk (alt_disk) provided."
  when: alt_disk | length > 0

- name: "Fail if a NIM LPP resource is not specified"
  ansible.builtin.fail:
    msg: "NIM LPP resource not specified"
  when: lpp_source_v | length > 0

- name: "Fail if spot is not provided"
  ansible.builtin.fail:
    msg: "Spot was not provided"
  when: spot_v | length > 0

- name: "Fail if NIM Master fileset's source has not been provided"
  ansible.builtin.fail:
    msg: "nim_master_fileset_src was not provided"
  when: nim_master_fileset_src | length > 0

- name: "Fail if phase was not provided"
  ansible.builtin.fail:
    msg: "You did not specify the phase"
  when: phase | length > 0

###############################################################################

- block:
    - name: "Create database backup file"
      ansible.builtin.import_tasks: create_backup.yml
      delegate_to: "{{ master_b }}"

    - name: Transfer the backup file to Controller machine
      ansible.builtin.import_tasks: fetch_to_controller.yml

    - name: Unconfigure the NIM database on "{{ master_b }}"
      ansible.builtin.raw: "nim -o unconfig master"
      delegate_to: "{{ master_b }}"
      register: command

    - name: Check for failure in Unconfiguring database on "{{ master_b }}"
      ansible.builtin.fail:
        msg: "Could not unconfigure database"
      when: command.rc != 0

    - name: Remove Master filesets from "{{ master_b }}"
      installp:
        action: "deinstall"
        install_list: bos.sysmgt.nim.master
      delegate_to: "{{ master_b }}"

    - name: Add the NIM "{{ master_b }}" as a “standalone” client to "{{ master_a }}"
      ansible.builtin.import_tasks: client_master_setup.yml

    - name: Perform Alt Disk Migration of Master using NIM
      ansible.builtin.import_tasks: migration.yml

    - name: Wait for 20 minutes after reboot so that the machine is up
      ansible.builtin.pause:
        minutes: 20

    - name: "Next Steps"
      ansible.builtin.debug:
        msg: "Migration has been done. Please run the role again with phase = db_restore to get the machine to previous state."

  when: phase == "backup_and_migration"

###############################################################################

- block:
    - name: Copy the NIM master fileset to "{{ master_b }}"
      ansible.builtin.import_tasks: copy_fileset.yml

    - name: Install NIM master filesets to "{{ master_b }}"
      installp:
        extend_fs: true
        device: "{{ nim_master_fileset_dest }}"
        install_list: bos.sysmgt.nim.master
      delegate_to: "{{ master_b }}"

    - name: Transfer the backup file to "{{ master_b }}"
      ansible.builtin.import_tasks: copy_to_b.yml

    - name: Restore the database
      ansible.builtin.raw: /usr/lpp/bos.sysmgt/nim/methods/m_restore_db {{ db_filename }}
      delegate_to: "{{ master_b }}"
      register: command

    - name: Check for failure in restoring database on "{{ master_b }}"
      ansible.builtin.fail:
        msg: "Could not restore database"
      when: command.rc != 0

    - ansible.builtin.debug: msg="Database restored, NIM Master - {{ master_b }} has been migrated and restored!!!"

  when: phase == "db_restore"
