---
- name: YuM Check-Update
  hosts: all
  gather_facts: true
  vars:
    name: "*"
    state: latest
    exclude: kernel*
  tasks:
    - name: Upgrade packages, excluding kernel related packages
      ansible.builtin.yum:
        name: "{{ name }}"
        state: "{{ state }}"
        exclude: "{{ exclude }}"

      register: output
    - ansible.builtin.debug:
        var: output
        cmd: ""
