---
- name: "FLRTVC on AIX playbook"
  hosts: aix
  gather_facts: no
  vars:
    apar: sec
    path: /usr/sys/inst.images
    check: no
    download_only: yes
    extend: yes
    protocol_v: "https"
    force_v: no
    clean_v: False
    verbose_v: yes
  collections:
    - ibm.power_aix

  tasks:
    - name: Install wget if it is not installed.
      import_role:
        name: power_aix_bootstrap
      vars:
        pkgtype: "wget"

    - name: "FLRTVC"
      flrtvc:
        path: "{{ path }}"
        verbose: "{{ verbose_v }}"
        apar: "{{ apar }}"
        force: "{{ force_v }}"
        clean: "{{ clean_v }}"
        check_only: "{{ check }}"
        download_only: "{{ download_only }}"
        extend_fs: "{{ extend }}"
        protocol: "{{ protocol_v }}"
      environment:
        PATH: "/usr/bin:/usr/sbin/:/opt/freeware/bin"
      register: result
    - debug: var=result
