---
- name: Tunfile manager for AIX
  hosts: all
  gather_facts: false
  vars:
    log_file: "/tmp/ansible_tunfile_debug.log"

  tasks:
    - name: "Save all tunables to a file"
      ibm.power_aix.tunfile_mgmt:
        action: save
        filename: /tunfile_mgmt_test
      register: tunfile_result
    - ansible.builtin.debug:
        var: tunfile_result

    - name: "Save only currently non default tunables to a file"
      ibm.power_aix.tunfile_mgmt:
        action: save
        filename: /tunfile_mgmt_test
        save_all_tunables: false
      register: tunfile_result
    - ansible.builtin.debug:
        var: tunfile_result

    - name: "Validate a tunable file in current context"
      ibm.power_aix.tunfile_mgmt:
        action: validate
        filename: /tunfile_mgmt_test
      register: tunfile_result
    - ansible.builtin.debug:
        var: tunfile_result

    - name: "Validate a tunable file in reboot context"
      ibm.power_aix.tunfile_mgmt:
        action: validate
        filename: /tunfile_mgmt_test
        validation_type: reboot
      register: tunfile_result
    - ansible.builtin.debug:
        var: tunfile_result

    - name: "Validate a tunable file in both reboot and current context"
      ibm.power_aix.tunfile_mgmt:
        action: validate
        filename: /tunfile_mgmt_test
        validation_type: both
      register: tunfile_result
    - ansible.builtin.debug:
        var: tunfile_result

    - name: "Modify all tunables of given component as default to a file"
      ibm.power_aix.tunfile_mgmt:
        action: modify
        filename: /tunfile_mgmt_test
        set_default: true
        component_to_set_dflt: schedo
      register: tunfile_result
    - ansible.builtin.debug:
        var: tunfile_result

    - name: "Modify specific dynamic tunables of given component in a file"
      ibm.power_aix.tunfile_mgmt:
        action: modify
        filename: /tunfile_mgmt_test
        tunables_with_values:
          nfso:
            client_delegation: 1
            nfs_rfc1323: 1
      register: tunfile_result
    - ansible.builtin.debug:
        var: tunfile_result

    - name: "Modify specific bosboot tunables of given component in a file"
      ibm.power_aix.tunfile_mgmt:
        action: modify
        filename: /tunfile_mgmt_test
        tunables_with_values:
          vmo:
            ame_mpsize_support: 1
      register: tunfile_result
    - ansible.builtin.debug:
        var: tunfile_result

    - name: "Modify specific restricted tunables of given component in a file"
      ibm.power_aix.tunfile_mgmt:
        action: modify
        filename: /tunfile_mgmt_test
        tunables_with_values:
          vmo:
            kernel_heap_psize: 128K
      register: tunfile_result
    - ansible.builtin.debug:
        var: tunfile_result

    - name: "Modify specific dynamic and bosboot tunables of given component in a file"
      ibm.power_aix.tunfile_mgmt:
        action: modify
        filename: /tunfile_mgmt_test
        tunables_with_values:
          vmo:
            ame_mpsize_support: 1
            ame_min_ucpool_size: 10
      register: tunfile_result
    - ansible.builtin.debug:
        var: tunfile_result

    - name: "Modify specific dynamic and bosboot tunables of given component in a file"
      ibm.power_aix.tunfile_mgmt:
        action: modify
        filename: /tunfile_mgmt_test
        tunables_with_values:
          vmo:
            ame_mpsize_support: 1
            ame_min_ucpool_size: 10
      register: tunfile_result
    - ansible.builtin.debug:
        var: tunfile_result

    - name: "Restore a file in current context"
    # This should be used when the changes are made only for the dynamic/some restrictive parameters. Changes will take place currently.
      ibm.power_aix.tunfile_mgmt:
        action: restore
        filename: /tunfile_mgmt_test
      register: tunfile_result
    - ansible.builtin.debug:
        var: tunfile_result

    - name: "Restore a file in reboot context"
    # This should be used when the changes made are also applicable for bosboot/reboot tunables. Changes will take place after the bosboot and reboot.
    # Ansible will show a message for bosboot and reboot.
    # If dynamic tunables are also there, still changes will take place only after bosboot and reboot.
    # This task just preserves the file in action as new /etc/tunables/nextboot file.
      ibm.power_aix.tunfile_mgmt:
        action: restore
        filename: /tunfile_mgmt_test
        make_nextboot: true
      register: tunfile_result
    - ansible.builtin.debug:
        var: tunfile_result
