---
- name: "FLRTVC on AIX playbook"
  hosts: all
  user: root
  gather_facts: no
  vars:
    apar: sec
    path: /usr/sys/inst.images
    check: no
    download_only: yes
    extend: yes
  collections:
  - ibm.power_aix

  tasks:
  - import_role:
      name: power_aix_bootstrap
    vars:
      pkgtype: "wget"

  - name: "FLRTVC"
    ibm.power_aix.flrtvc:
      path: "{{ path }}"
      verbose: yes
      apar: "{{ apar }}"
      force: no
      clean: False
      check_only: "{{ check }}"
      download_only: "{{ download_only }}"
      extend_fs: "{{ extend }}"
    register: result
  - debug: var=result
