---
- name: "tunfile manager for AIX"
  hosts: all
  gather_facts: no
  vars:
    log_file: "/tmp/ansible_tunfile_debug.log"

  tasks:
    - name: "Save all tunables to a file"
      tunfile_mgmt:
        action: save
        filename: /tunfile_mgmt_test
      register: tunfile_result
    - debug: var=tunfile_result

    - name: "Save only currently non default tunables to a file"
      tunfile_mgmt:
        action: save
        filename: /tunfile_mgmt_test
        save_all_tunables: False
      register: tunfile_result
    - debug: var=tunfile_result

    - name: "Validate a tunable file in current context"
      tunfile_mgmt:
        action: validate
        filename: /tunfile_mgmt_test
      register: tunfile_result
    - debug: var=tunfile_result

    - name: "Validate a tunable file in reboot context"
      tunfile_mgmt:
        action: validate
        filename: /tunfile_mgmt_test
        validation_type: reboot
      register: tunfile_result
    - debug: var=tunfile_result

    - name: "Validate a tunable file in both reboot and current context"
      tunfile_mgmt:
        action: validate
        filename: /tunfile_mgmt_test
        validation_type: both
      register: tunfile_result
    - debug: var=tunfile_result

    - name: "Modify all tunables of given component as default to a file"
      tunfile_mgmt:
        action: modify
        filename: /tunfile_mgmt_test
        set_default: True
        component_to_set_dflt: schedo
      register: tunfile_result
    - debug: var=tunfile_result

    - name: "Modify specific dynamic tunables of given component in a file"
      tunfile_mgmt:
        action: modify
        filename: /tunfile_mgmt_test
        tunables_with_values:
          nfso:
            client_delegation: 1
            nfs_rfc1323: 1
      register: tunfile_result
    - debug: var=tunfile_result

    - name: "Modify specific bosboot tunables of given component in a file"
      tunfile_mgmt:
        action: modify
        filename: /tunfile_mgmt_test
        tunables_with_values:
          vmo:
            ame_mpsize_support: 1
      register: tunfile_result
    - debug: var=tunfile_result

    - name: "Modify specific restricted tunables of given component in a file"
      tunfile_mgmt:
        action: modify
        filename: /tunfile_mgmt_test
        tunables_with_values:
          vmo:
            kernel_heap_psize: 128K
      register: tunfile_result
    - debug: var=tunfile_result

    - name: "Modify specific dynamic and bosboot tunables of given component in a file"
      tunfile_mgmt:
        action: modify
        filename: /tunfile_mgmt_test
        tunables_with_values:
          vmo:
            ame_mpsize_support: 1
            ame_min_ucpool_size: 10
      register: tunfile_result
    - debug: var=tunfile_result

    #- name: "Modify wrong tunables of given component in a file"
    #  tunfile_mgmt:
    #    action: modify
    #    filename: /tunfile_mgmt_test
    #    tunables_with_values:
    #      vmo:
    #        wrong_tun_params: 1
    #  register: tunfile_result
    #- debug: var=tunfile_result

    - name: "Modify specific dynamic and bosboot tunables of given component in a file"
      tunfile_mgmt:
        action: modify
        filename: /tunfile_mgmt_test
        tunables_with_values:
          vmo:
            ame_mpsize_support: 1
            ame_min_ucpool_size: 10
      register: tunfile_result
    - debug: var=tunfile_result

    - name: "Restore a file in current context"
    #This should be used when the changes are made only for the dynamic/some restrictive parameters. Changes will take place currently.
      tunfile_mgmt:
        action: restore
        filename: /tunfile_mgmt_test
      register: tunfile_result
    - debug: var=tunfile_result

    - name: "Restore a file in reboot context"
    # This should be used when the changes made are also applicable for bosboot/reboot tunables. Changes will take place after the bosboot and reboot.
    # Ansible will show a message for bosboot and reboot.
    # If dynamic tunables are also there, still changes will take place only after bosboot and reboot.
    # This task just preserves the file in action as new /etc/tunables/nextboot file.
      tunfile_mgmt:
        action: restore
        filename: /tunfile_mgmt_test
        make_nextboot: True
      register: tunfile_result
    - debug: var=tunfile_result

    #- name: "Restore a file which also includes wrong tunable parameter"
    # Ansible will give a warning for this particular wrong tunable and skip it.
    # Task will carry on for the other valid tunables.
    #  tunfile_mgmt:
    #    action: restore
    #    filename: /tunfile_mgmt_test
    #  register: tunfile_result
    #- debug: var=tunfile_result
