---
- name: Install wget using dnf
  hosts: all
  user: root
  gather_facts: false

  tasks:
    - name: Install wget
      ansible.builtin.dnf:
        name: wget
        state: present
      environment:
        PATH: /opt/freeware/bin
      vars:
        ansible_python_interpreter: /opt/freeware/bin/python3
