---
# ptsiamis@gmail.com
# Demo playbook
# Create a local nginx with the patches
# Download patches with playbook:
# demo_shell_flrtvc_wget_ifix.yml
- name: "Demo install ifix from flrtvc from local patch server"
  hosts: all
  gather_facts: false
  vars:
    localpatchserver: "192.168.1.1"
    localpatchpath: "ifix"
    protocol: "https"
    apar_csv: "/tmp/apar.csv"
    flrtvczip: "{{protocol}}://{{localpatchserver}}/{{localpatchpath}}/FLRTVC-latest.zip"
    apar_csv_url: "{{protocol}}://{{localpatchserver}}/{{localpatchpath}}/apar.csv"
    debug: false
  tasks:
    - name: Download apar.csv to /tmp/apar.csv from {{ apar_csv_url }}
      ansible.builtin.get_url:
        url: "{{ apar_csv_url }}"
        dest: "{{ apar_csv }}"
        validate_certs: false

    - name: Install all security interim fixes
      ibm.power_aix.flrtvc:
        apar: "sec"
        verbose: true
        protocol: "{{ protocol }}"
        force: false
        clean: false
        flrtvczip: "{{ flrtvczip }}"
        localpatchserver: "{{ localpatchserver }}"
        localpatchpath: "{{ localpatchpath }}"
        csv: "{{ apar_csv }}"
      register: reg_install
      environment:
        http_proxy: ""
        https_proxy: ""
        PATH: "/usr/bin:/usr/sbin:/usr/local/bin:/opt/freeware/bin"

    - name: Debug reg_install
      ansible.builtin.debug:
        var: reg_install
      when: debug
