---
- name: "Reboot the machine"
  hosts: aix
  gather_facts: false
  vars:
    log_file: "/tmp/ansible_reboot_debug.log"
    pre_reboot_delay_v: 0
    post_reboot_delay_v: 0
    reboot_timeout_v: 0
    test_command_v: ""

  tasks:
    - name: Reboot the machine
      ibm.power_aix.reboot:
        pre_reboot_delay: "{{ pre_reboot_delay_v }}"
        post_reboot_delay: "{{ post_reboot_delay_v }}"
        reboot_timeout: "{{ reboot_timeout_v }}"
        test_command: "{{ test_command_v }}"
      register: reboot_result

    - ansible.builtin.debug:
        var: reboot_result
