---
- name: "USER on AIX"
  hosts: "{{host_name}}"
  gather_facts: no
  vars:
    host_name: all
    user_name: aixguest
    password_val: abc12345
    attribute_home: /home/test/aixguest
  collections:
    ibm.power_aix
  tasks:
    - name: Create user
      user:
        state: present
        name: "{{user_name}}"
        change_passwd_on_login: False
        password: "{{password_val}}"
        attributes:
          home: "{{attribute_home}}"
          data: 1272
    - name: Modify user
      user:
        state: modify
        name: "{{user_name}}"
        attributes:
          admin: true
    - name: Delete user
      user:
        state: absent
        name: "{{user_name}}"
        remove_homedir: False
