---
- name: "VIOS alternate disk copy on AIX"
  hosts: nimserver
  gather_facts: no
  vars:
#    time_limit_v:  "mm/dd/yyyy hh:mm"
#VIOSes and the disks associated to it to do alt_disk_copy or alt_disk_clean.
    target_vios_disks_v: 
      - "vios1": ["hdisk1"] 
      - "vios2": ["hdisk2"]
    
  tasks:
    - name: "Perform an alternate disk copy on VIOS"
      nim_vios_alt_disk:
        action: alt_disk_copy
        targets: "{{ target_vios_disks_v }}"        
#       time_limit: "{{ time_limit_v }}"
      register: altdisk_copy_result

    - debug: var=altdisk_copy_result

    - name: "Perform an alternate disk cleanup on VIOS"
      nim_vios_alt_disk:
        targets: "{{target_vios_disks_v}}"
        action: alt_disk_clean
        vios_status: "{{ altdisk_copy_result.status }}"
        nim_node: "{{ altdisk_copy_result.nim_node }}"

      register: altdisk_result

    - debug: var=altdisk_result