---
- name: "Install an SQL database server"
  hosts: all
  gather_facts: true
  vars:
    package: mariadb-server
  tasks:
    - name: "Increase File System size for /opt"
      community.general.aix_filesystem:
        filesystem: /opt
        size: +350M
        state: present
      when: ansible_distribution == 'AIX'

    - name: "Increase File System size for /var"
      community.general.aix_filesystem:
        filesystem: /var
        size: +250M
        state: present
      when: ansible_distribution == 'AIX'

    - name: "Yum install {{ package }}"
      ansible.builtin.yum:
        name: "{{ package }}"
        state: latest
      register: output
    - ansible.builtin.debug:
        var: output
