---
- name: NIM check on AIX playbook
  hosts: nimserver
  gather_facts: false

  tasks:
    - name: AIX NIM
      nim:
        action: check
      register: result
    - name: Display nim check result
      ansible.builtin.debug:
        var: result
