---
- name: "Print the mpio related information"
  hosts: "{{ hosts_val }}"
  gather_facts: yes
  vars:
    hosts_val: all
    log_file: "/tmp/ansible_mpio_debug.log"
  collections:
  - ibm.power_aix

  tasks:
    - name: "Gather the mpio info"
      mpio:

    - name: "Gather specific device  mpio info"
      mpio:
        device: "IBMSVC"

    - name: "Gather specific absent device  mpio info"
      mpio:
        device: "ansibleNegativeTest"

    - name: Print the paths
      debug:
        var: ansible_facts.mpio.paths
