---
# PREREQUISITES:

- name: "nim_master_migration demo"
  hosts: "{{ hosts_val }}"
  gather_facts: false
  vars:
    hosts_val: all
    log_file: "/tmp/ansible_mpio_debug.log"
  remote_user: root
  collections:
    - ibm.power_aix
  tasks:
    - import_role:
        name: nim_master_migration
      vars:
        master_a: ansible-nim1
        master_b: "fvtfleet1-lp1"
        alt_disk: "hdisk1"
        db_filename: "db_backupfile"
        lpp_source_v: "2317A_73D"
        spot_v: "2317A_73D_spot"
        nim_master_fileset_src: "~/bos.sysmgt"
        nim_master_fileset_dest: "~/bos.sysmgt"
        phase: db_restore
        db_file_controller: "~/db_backupfile"
        # phase: backup_and_migration
        