---
- name: "Print the LVM related information"
  hosts: quimby05
  gather_facts: yes
  vars:
    log_file: "/tmp/ansible_lvmfacts_debug.log"

  tasks:
    - name: "Gather all lvm facts"
      lvm_facts:
    - name: "Gather VG facts"
      lvm_facts:
        name: all
        component: vg
    - name: "Gather LV facts"
      lvm_facts:
        name: all
        component: lv
    - name: "Update PV facts to existing LVM facts"
      lvm_facts:
        name: all
        component: pv
        lvm: "{{ ansible_facts.LVM }}"
