---
- name: NIM check on AIX playbook
  hosts: "{{ host_name }}"
  user: root
  vars:
    host_name: nimserver
    download_dir_val: /usr/sys/inst.images
    oslevel_val: Latest
  gather_facts: false
  become: true

  tasks:
    - name: Check, download and create the NIM resource to install latest updates
      ibm.power_aix.nim_suma:
        action: download
        targets: "{{ nim_clients | default(omit) }}"
        oslevel: "{{ oslevel_val }}"
        download_dir: "{{ download_dir_val }}"
      register: result
    - ansible.builtin.debug:
        var: result
        cmd: ""
