---
- name: "vios-health-checker on NIM master"
  hosts: nimmaster
  gather_facts: no
  collections:
  - ibm.power_aix
  
  tasks:
# Install/Update vios health checker on NIM master.
  - name: Install the vioshc on NIM master
    import_role:
       name: power_aix_vioshc