---
- name: "Print the LVM related information"
  hosts: "{{ hosts_val }}"
  gather_facts: yes
  vars:
    hosts_val: all
    log_file: "/tmp/ansible_lvmfacts_debug.log"
  collections:
  - ibm.power_aix

  tasks:
    - name: "Gather all lvm facts"
      lvm_facts:
    - name: "Gather VG facts"
      lvm_facts:
        name: all
        component: vg
    - name: "Gather LV facts"
      lvm_facts:
        name: all
        component: lv
    - name: "Update PV facts to existing LVM facts"
      lvm_facts:
        name: all
        component: pv
        lvm: "{{ ansible_facts.LVM }}"
