---
- name: "Demo for mktun module"
  hosts: all
  gather_facts: yes
  vars:
    log_file: "/tmp/ansible_mktun_debug.log"
    ip_v4_address_src: 10.10.11.72
    ip_v4_address_dest: 10.10.11.98
    var_ah_algo: HMAC_MD5
    var_esp_algo: DES_CBC_8
    var_esp_spi: 12345
    var_id_1: 3
    var_id_2: 4
    var_id_3: 5

  tasks:
    - name: Create and activate a manual IPv4 tunnel
      ibm.power_aix.mktun:
        manual:
          ipv4:
          - src:
              address: "{{ ip_v4_address_src }}"
              ah_algo: "{{ var_ah_algo }}"
              esp_algo: "{{ var_esp_algo }}"
            dst:
              address: "{{ ip_v4_address_dest }}"
              esp_spi: "{{ var_esp_algo }}"

    - name: Export IPv4 tunnel definition for given tunnel id on srchost
      ibm.power_aix.mktun:
        manual:
          ipv4:
            - id: "{{ var_id_1 }}"
              export: yes
      register: export_result
      when: 'inventory_hostname == srchost'

    - name: Import IPv4 tunnel definition on dsthost
      ibm.power_aix.mktun:
        manual:
          import_ipv4: '{{ export_result.export_ipv4 }}'
      when: 'inventory_hostname == dsthost'

    - name: Remove manual IPv4 tunnel with given id from tunnel database
      ibm.power_aix.mktun:
        manual:
          ipv4:
            - id: "{{ var_id_1 }}"
              state: absent

    - name: Try again to Remove manual IPv4 tunnel with given id from tunnel database
      ibm.power_aix.mktun:
        manual:
          ipv4:
            - id: "{{ var_id_1 }}"
              state: absent

    - name: Deactivate manual IPv4 tunnel with id 4
      ibm.power_aix.mktun:
        manual:
          ipv4:
            - id: "{{ var_id_2 }}"
              state: defined

    - name: Activate manual IPv4 tunnel with id 5
      ibm.power_aix.mktun:
        manual:
          ipv4:
            - id: "{{ var_id_3 }}"
              state: active

    - name: Gather the tunnel facts
      ibm.power_aix.mktun:

    - name: Print the tunnel facts
      debug:
        var: ansible_facts.tunnels
