---
- name: "Print the mpio related information"
  hosts: all
  gather_facts: yes
  vars:
    device: "IBMSVC"
    absent_device: "ansibleNegativeTest"
    log_file: "/tmp/ansible_mpio_debug.log"
  collections:
    - ibm.power_aix

  tasks:
    - name: "Gather the mpio info"
      mpio:

    - name: "Gather specific device  mpio info"
      ibm.power_aix.mpio:
        device: "{{ device }}"

    - name: "Gather specific absent device  mpio info"
      mpio:
        device: "{{ absent_device }}"

    - name: Print the paths
      debug:
        var: ansible_facts.mpio.paths
