#!/usr/bin/python
# -*- coding: utf-8 -*-

# Copyright: (c) 2020- IBM, Inc
# GNU General Public License v3.0+ (see COPYING or https://www.gnu.org/licenses/gpl-3.0.txt)

from __future__ import (absolute_import, division, print_function)
__metaclass__ = type

DOCUMENTATION = r'''
---
module: clvupdate
short_description: Run the AIX clvupdate command to clean up failed Live Update operations
version_added: "2.2.0"
author:
  - "Nitish K Mishra (@nitismis)"
description:
  - Wrapper around the AIX C(clvupdate) command, which cleans up the system
    after a failed Live Update operation and the default cleanup attempt has
    not been successful.
  - The module allows you to call clvupdate with specific flags such as removing
    surrogate boot disks, unlocking the Live Update lock, ignoring kernel state
    or status, using an alternate liveupdate configuration file, etc.
  - For full command semantics, see the AIX documentation for clvupdate.
requirements:
  - AIX 7.2 or later.
  - The C(clvupdate) binary must be available in C($PATH) on the managed node.
options:
  remove_surrogate_disks:
    description:
      - Remove surrogate boot disks created by a failed Live Update in PowerVC
        mode.
      - Maps to C(-d).
    type: bool
    default: false

  ignore_state:
    description:
      - Ignore the Live Update kernel state and proceed with cleanup anyway.
      - Use this when the partition has been rebooted after a failed Live
        Update attempt, but cleanup is still required.
      - Maps to C(-e).
    type: bool
    default: false

  unlock_only:
    description:
      - Unlock the Live Update lock only, without doing a full cleanup.
      - Maps to C(-l).
    type: bool
    default: false

  run_error_scripts:
    description:
      - Run only the C(LVUP_ERROR) phase scripts from other system components,
        instead of a full cleanup.
      - Maps to C(-n).
    type: bool
    default: false

  ignore_status:
    description:
      - Ignore the Live Update kernel status and proceed with cleanup anyway.
      - Use this when clvupdate reports that some live update processes might
        still be running, but you know they are not.
      - Maps to C(-u).
    type: bool
    default: false

  force_original_shutdown:
    description:
      - Force the original partition to be shut down before cleanup proceeds.
      - Use this when the workload was moved to a surrogate partition after
        blackout time and the original partition is still active.
      - Maps to C(-o).
    type: bool
    default: false

  reset_state_only:
    description:
      - Reset the Live Update kernel state and status only, without performing
        a full cleanup.
      - Use this when a manual cleanup was already performed but kernel
        variables were not reset.
      - Maps to C(-r).
    type: bool
    default: false

  remove_lvup_vg:
    description:
      - Remove the temporary C(lvup_rootvg) volume group that was used by the
        surrogate partition during Live Update.
      - Requires valid PowerVC authentication via C(pvcauth).
      - Maps to C(-v).
    type: bool
    default: false

  alt_hmc_hostname:
    description:
      - Host name or IP address of an alternative HMC for authentication.
      - Use this when the HMC used during Live Update is unresponsive.
      - Maps to C(-a HMChostname).
    type: str

  alt_hmc_username:
    description:
      - User name for the alternative HMC for authentication.
      - Must have required privileges on the HMC.
      - Maps to C(-U HMCusername).
    type: str

  alt_cf_file:
    description:
      - Path of an alternative C(liveupdate.cf) file generated by a previous
        Live Update operation.
      - Use this when you want to undo changes from a specific failed Live
        Update attempt.
      - Maps to C(-f AltCfFile).
    type: str

  executable:
    description:
      - Override path to the C(clvupdate) binary if it is not in C($PATH).
    type: str
    default: clvupdate
'''

EXAMPLES = r'''
- name: Basic cleanup using default liveupdate.cf
  ibm.power_aix.clvupdate:
  register: result

- name: Remove Live Update lock only
  ibm.power_aix.clvupdate:
    unlock_only: true

- name: Cleanup after rebooted partition, ignoring kernel state
  ibm.power_aix.clvupdate:
    ignore_state: true

- name: Ignore Live Update status and force cleanup
  ibm.power_aix.clvupdate:
    ignore_status: true

- name: Remove surrogate boot disks after failed PowerVC Live Update
  ibm.power_aix.clvupdate:
    remove_surrogate_disks: true

- name: Reset Live Update kernel variables only
  ibm.power_aix.clvupdate:
    reset_state_only: true

- name: Use alternate liveupdate.cf file from previous attempt
  ibm.power_aix.clvupdate:
    alt_cf_file: /var/adm/ras/liveupdate/liveupdate.cf.alt

- name: Use alternate HMC for cleanup coordination
  ibm.power_aix.clvupdate:
    alt_hmc_hostname: hmc1.example.com
    alt_hmc_username: hmcuser
'''

RETURN = r'''
cmd:
  description: Full command line executed.
  returned: always
  type: str
rc:
  description: Return code from the C(clvupdate) command.
  returned: always
  type: int
stdout:
  description: Standard output from the C(clvupdate) command.
  returned: when rc is not 0 or when verbosity is requested
  type: str
stderr:
  description: Standard error from the C(clvupdate) command.
  returned: when rc is not 0
  type: str
changed:
  description: Whether the module caused any changes.
  returned: always
  type: bool
'''

from ansible.module_utils.basic import AnsibleModule


def build_clvupdate_cmd(params):
    """
    Build the clvupdate command line from module parameters.
    """
    executable = params.get('executable') or 'clvupdate'
    cmd = [executable]

    # flag mappings
    if params.get('remove_surrogate_disks'):
        cmd.append('-d')
    if params.get('ignore_state'):
        cmd.append('-e')
    if params.get('unlock_only'):
        cmd.append('-l')
    if params.get('run_error_scripts'):
        cmd.append('-n')
    if params.get('ignore_status'):
        cmd.append('-u')
    if params.get('force_original_shutdown'):
        cmd.append('-o')
    if params.get('reset_state_only'):
        cmd.append('-r')
    if params.get('remove_lvup_vg'):
        cmd.append('-v')

    # Options with values
    if params.get('alt_hmc_hostname'):
        cmd.extend(['-a', params['alt_hmc_hostname']])
    if params.get('alt_hmc_username'):
        cmd.extend(['-U', params['alt_hmc_username']])
    if params.get('alt_cf_file'):
        cmd.extend(['-f', params['alt_cf_file']])

    return cmd


def run_module():
    argument_spec = dict(
        remove_surrogate_disks=dict(type='bool', default=False),
        ignore_state=dict(type='bool', default=False),
        unlock_only=dict(type='bool', default=False),
        run_error_scripts=dict(type='bool', default=False),
        ignore_status=dict(type='bool', default=False),
        force_original_shutdown=dict(type='bool', default=False),
        reset_state_only=dict(type='bool', default=False),
        remove_lvup_vg=dict(type='bool', default=False),
        alt_hmc_hostname=dict(type='str'),
        alt_hmc_username=dict(type='str'),
        alt_cf_file=dict(type='str'),
        executable=dict(type='str', default='clvupdate'),
    )

    module = AnsibleModule(
        argument_spec=argument_spec,
        supports_check_mode=True,
    )

    params = module.params

    # HMC username should not be set without hostname.
    if params.get('alt_hmc_username') and not params.get('alt_hmc_hostname'):
        module.fail_json(
            msg="alt_hmc_username requires alt_hmc_hostname to be set",
        )

    cmd = build_clvupdate_cmd(params)
    cmd_str = ' '.join(cmd)

    # Check mode: don't execute, just report what would happen.
    if module.check_mode:
        module.exit_json(
            changed=False,
            cmd=cmd_str,
            rc=0,
            stdout='',
            stderr='',
        )

    rc, stdout, stderr = module.run_command(cmd)

    if rc != 0:
        module.fail_json(
            msg="clvupdate command failed",
            cmd=cmd_str,
            rc=rc,
            stdout=stdout,
            stderr=stderr,
            changed=False,
        )

    # A successful clvupdate run implies changes were made
    # or at least the cleanup was (re)attempted.
    module.exit_json(
        changed=True,
        cmd=cmd_str,
        rc=rc,
        stdout=stdout,
        stderr=stderr,
    )


def main():
    run_module()


if __name__ == '__main__':
    main()
