name: run ibm.power_aix collection unit tests

# run unit test during pull request to dev-collection
on:
  pull_request:
    branches: [ dev-collection ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  unit-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ansible_collections/ibm/power_aix
    strategy:
      matrix:
        python-version: ['3.7']
        
    name: running unit tests with python ${{ matrix.python-version }}
    steps:
      - name: checkout repository
        uses: actions/checkout@v2
        with:
          path: ansible_collections/ibm/power_aix
        
      - name: setup python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
    
      - name: install ansible
        run: |
          python -m pip install --upgrade pip
          python -m pip install ansible
          
      - name: install python modules needed for unit testing
        run: |
          make install-unit-test-requirements
          
      - name: run unit tests
        run: |
          make unit-test
